---
title: "wei_wang"
author: "Talia_Karasov"
date: "8/27/2019"
output: 
  html_document: 
    fig_height: 4
    fig_width: 3.5
    self_contained: no
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width = 12, fig.height = 8, echo = FALSE, warning = FALSE, message = FALSE, cache = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reshape2)
library('dplyr')
library("ggplot2")
library(RCurl)
library(googlesheets4)
library(googledrive)
library(Rmisc)
library(ggpubr)
mycolors=c("#c8588c","#6aa74d","#8d70c9","#b69140","#49adad","#cc5b43")
```

Read in map of who was where
```{r}
fileUrl <- ("https://docs.google.com/spreadsheets/d/1ar1stJXBPljPWMtrY5QcABxTfU-0Wv7GUyQ6Y6AbXvI/edit#gid=0")
fileCSV <- read_sheet(ss = fileUrl)

pos_genot_map=fileCSV[,c("position","Genotype")]

```

Read in data from green pixels and merge with pos map
```{r}
green_pixels = read.table("~/work_main/abt6_projects8/Pseudomonas_mapping/data/infection_experiments/august_2019/process_pixels_all.txt", sep="\t", header=T)

green_pixels = merge(pos_genot_map, green_pixels, by.x = "position", by.y = "position")

green_pixels = subset(green_pixels, Genotype!="NA")

greenp_ww = green_pixels[green_pixels$Plate %in% c("plate1_1_uncover_23082019", "plate1_2_uncover_2382019"),]

greenp_mutant = green_pixels[green_pixels$Plate %in% c("plate2_1_uncover_2382019", "plate3_2_uncover_2382019"),]


```

Now plot the green pixels
```{r}
greenp_ww$Genotype = as.factor(greenp_ww$Genotype)


#greenp_ww$Genotype = factor(greenp_ww$Genotype, levels = c("C", "DC3000", "WT", "AVRE", "HRC"))

the_means = greenp_ww %>% group_by(Genotype) %>% dplyr::summarise(mean = mean(Green_pixels, na.rm=T), sd = sd(Green_pixels, na.rm=T), se = sd(Green_pixels, na.rm=T) / length(Green_pixels), log10_mean = mean(log10(Green_pixels + 1), na.rm = T), log10_se =  sd(log10(Green_pixels + 1))/length(Green_pixels))

base = ggplot(data = the_means, aes(x=Genotype, y=mean, colour=Genotype))

p2 = base + geom_errorbar(aes(ymin=(mean-se), ymax=(mean+se)), width=.25) +
 theme_light() + 
  geom_jitter(data = greenp_ww, aes(x=Genotype, y=(Green_pixels)), width=0.1, alpha=0.5) + 
  ylab("Green Pixel Number") +
  scale_color_manual(values = mycolors) 

base_log = ggplot(data = the_means, aes(x=Genotype, y=log10_mean, colour=Genotype))

p3 =  base_log + geom_errorbar(aes(ymin=(log10_mean-log10_se), ymax=(log10_mean+log10_se)), width=.25) +
 theme_light() + 
  geom_jitter(data = greenp_ww, aes(x=Genotype, y=log10(Green_pixels + 1)), width=0.1, alpha=0.5) + 
  ylab("log10(Green Pixel Number)") +
  scale_color_manual(values = mycolors) 

plot_grid(p2,p3, nrow = 2)

my_comparisons <- list( c("C", "DC3000"), c("C", "P5"), c("P5", "P22"), c("P5", "P13"))

my_comparisons = list(c(1,2))

p2 + stat_compare_means(aes(x=Genotype, y=(Green_pixels)), data = greenp_ww)


p2 + 
  stat_compare_means(aes(x=Genotype, y=(Green_pixels)), data = greenp_ww)
#  theme(legend.position = c(0.95, 0.95),legend.justification = c("right", "top")

```

```{r}
p4 = ggplot(data = greenp_ww, aes(x=Genotype, y=Green_pixels)) +
  stat_compare_means(comparisons = list(c(1,2), c(1,3), c(1,4), c(1,5), c(4,5), c(3,5)), method = "wilcox.test") +
  geom_boxplot(data = greenp_ww, aes(x=Genotype, y=Green_pixels, colour=Genotype)) +
  geom_jitter(data = greenp_ww, aes(x=Genotype, y=(Green_pixels)), width=0.1, alpha=0.5) + 
  ylab("Green Pixels") + 
  scale_color_manual(values = mycolors) + 
  theme_light()
pdf("~/Google Drive/pseudomonas_association_mapping/Experiments/infection_8.2019/ww_8_2019_scatter.pdf", useDingbats = FALSE, family = "ArialMT")
p4
dev.off()
      
```
Let's compare all genotypes to Control
```{r}
ww = lm(data = greenp_ww, (Green_pixels) ~ Genotype)
kw = kruskal.test(data = greenp_ww, (Green_pixels) ~ Genotype)
pairwise.wilcox.test(greenp_ww$Green_pixels, greenp_ww$Genotype,
                 p.adjust.method = "none")
```

Overall the results suggest that p5.B9 reduces the growth of the plant less. But the cfu suggests that there is some other weird microbe there...so...we need to figure out how to do this sterile. The results just got pretty crappy.
